# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 410, 431, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image2Editor_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image2Editor_label.setObjectName("image2Editor_label")
        self.verticalLayout.addWidget(self.image2Editor_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image2EditorFreehand_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.image2EditorFreehand_pushButton.setObjectName("image2EditorFreehand_pushButton")
        self.horizontalLayout.addWidget(self.image2EditorFreehand_pushButton)
        self.image2EditorLine_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.image2EditorLine_pushButton.setObjectName("image2EditorLine_pushButton")
        self.horizontalLayout.addWidget(self.image2EditorLine_pushButton)
        self.image2EditorFill_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.image2EditorFill_pushButton.setObjectName("image2EditorFill_pushButton")
        self.horizontalLayout.addWidget(self.image2EditorFill_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image2EditorColor_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image2EditorColor_label.setObjectName("image2EditorColor_label")
        self.horizontalLayout_2.addWidget(self.image2EditorColor_label)
        self.image2EditorColor_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.image2EditorColor_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.image2EditorColor_lineEdit.setObjectName("image2EditorColor_lineEdit")
        self.horizontalLayout_2.addWidget(self.image2EditorColor_lineEdit)
        self.image2EditorPenPixelSize_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image2EditorPenPixelSize_label.setObjectName("image2EditorPenPixelSize_label")
        self.horizontalLayout_2.addWidget(self.image2EditorPenPixelSize_label)
        self.image2EditorPenPixelSize_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.image2EditorPenPixelSize_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.image2EditorPenPixelSize_lineEdit.setObjectName("image2EditorPenPixelSize_lineEdit")
        self.horizontalLayout_2.addWidget(self.image2EditorPenPixelSize_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 280, 431, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.image1EditorFreehand_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.image1EditorFreehand_pushButton.setObjectName("image1EditorFreehand_pushButton")
        self.horizontalLayout_3.addWidget(self.image1EditorFreehand_pushButton)
        self.image1EditorLine_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.image1EditorLine_pushButton.setObjectName("image1EditorLine_pushButton")
        self.horizontalLayout_3.addWidget(self.image1EditorLine_pushButton)
        self.image1EditorFill_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.image1EditorFill_pushButton.setObjectName("image1EditorFill_pushButton")
        self.horizontalLayout_3.addWidget(self.image1EditorFill_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.image1EditorColor_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.image1EditorColor_label.setObjectName("image1EditorColor_label")
        self.horizontalLayout_4.addWidget(self.image1EditorColor_label)
        self.image1EditorColor_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.image1EditorColor_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.image1EditorColor_lineEdit.setObjectName("image1EditorColor_lineEdit")
        self.horizontalLayout_4.addWidget(self.image1EditorColor_lineEdit, 0, QtCore.Qt.AlignVCenter)
        self.image1EditorPenPixelSize_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.image1EditorPenPixelSize_label.setObjectName("image1EditorPenPixelSize_label")
        self.horizontalLayout_4.addWidget(self.image1EditorPenPixelSize_label)
        self.image1EditorPenPixelSize_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.image1EditorPenPixelSize_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.image1EditorPenPixelSize_lineEdit.setObjectName("image1EditorPenPixelSize_lineEdit")
        self.horizontalLayout_4.addWidget(self.image1EditorPenPixelSize_lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 431, 27))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.loadImage1_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.loadImage1_pushButton.setObjectName("loadImage1_pushButton")
        self.horizontalLayout_7.addWidget(self.loadImage1_pushButton)
        self.loadImage2_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.loadImage2_pushButton.setObjectName("loadImage2_pushButton")
        self.horizontalLayout_7.addWidget(self.loadImage2_pushButton)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 431, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.zoom_label = QtWidgets.QLabel(self.layoutWidget)
        self.zoom_label.setObjectName("zoom_label")
        self.horizontalLayout_6.addWidget(self.zoom_label)
        self.zoom_slider = QtWidgets.QSlider(self.layoutWidget)
        self.zoom_slider.setMaximum(100)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName("zoom_slider")
        self.horizontalLayout_6.addWidget(self.zoom_slider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zoomCenterX_label = QtWidgets.QLabel(self.layoutWidget)
        self.zoomCenterX_label.setObjectName("zoomCenterX_label")
        self.horizontalLayout_5.addWidget(self.zoomCenterX_label)
        self.zoomCenterX_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.zoomCenterX_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.zoomCenterX_lineEdit.setObjectName("zoomCenterX_lineEdit")
        self.horizontalLayout_5.addWidget(self.zoomCenterX_lineEdit)
        self.zoomCenterY_label = QtWidgets.QLabel(self.layoutWidget)
        self.zoomCenterY_label.setObjectName("zoomCenterY_label")
        self.horizontalLayout_5.addWidget(self.zoomCenterY_label)
        self.zoomCenterY_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.zoomCenterY_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.zoomCenterY_lineEdit.setObjectName("zoomCenterY_lineEdit")
        self.horizontalLayout_5.addWidget(self.zoomCenterY_lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(480, 30, 511, 511))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 507, 507))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.imageArea_QLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.imageArea_QLabel.setGeometry(QtCore.QRect(0, 0, 509, 509))
        self.imageArea_QLabel = QtWidgets.QLabel()
        self.imageArea_QLabel.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.imageArea_QLabel.setAutoFillBackground(True)
        self.imageArea_QLabel.setText("")
        self.imageArea_QLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.imageArea_QLabel.setObjectName("imageArea_QLabel")
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.imageArea_QLabel)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 180, 431, 80))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.image1Alpha_label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.image1Alpha_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image1Alpha_label_2.setObjectName("image1Alpha_label_2")
        self.verticalLayout_5.addWidget(self.image1Alpha_label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.image1Alpha_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.image1Alpha_label.setObjectName("image1Alpha_label")
        self.horizontalLayout_8.addWidget(self.image1Alpha_label)
        self.imageAlpha_slider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.imageAlpha_slider.setEnabled(True)
        self.imageAlpha_slider.setMinimum(0)
        self.imageAlpha_slider.setMaximum(255)
        self.imageAlpha_slider.setPageStep(32)
        self.imageAlpha_slider.setProperty("value", 128)
        self.imageAlpha_slider.setTracking(True)
        self.imageAlpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.imageAlpha_slider.setInvertedAppearance(False)
        self.imageAlpha_slider.setInvertedControls(False)
        self.imageAlpha_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.imageAlpha_slider.setObjectName("imageAlpha_slider")
        self.horizontalLayout_8.addWidget(self.imageAlpha_slider)
        self.image2Alpha_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.image2Alpha_label.setObjectName("image2Alpha_label")
        self.horizontalLayout_8.addWidget(self.image2Alpha_label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image2Editor_label.setText(_translate("MainWindow", "Image2 Editor"))
        self.image2EditorFreehand_pushButton.setText(_translate("MainWindow", "Freehand"))
        self.image2EditorLine_pushButton.setText(_translate("MainWindow", "Line"))
        self.image2EditorFill_pushButton.setText(_translate("MainWindow", "Fill"))
        self.image2EditorColor_label.setText(_translate("MainWindow", "Color"))
        self.image2EditorColor_lineEdit.setText(_translate("MainWindow", "128"))
        self.image2EditorPenPixelSize_label.setText(_translate("MainWindow", "PenPixelSize"))
        self.image2EditorPenPixelSize_lineEdit.setText(_translate("MainWindow", "5"))
        self.label_12.setText(_translate("MainWindow", "Image1 Editor"))
        self.image1EditorFreehand_pushButton.setText(_translate("MainWindow", "Freehand"))
        self.image1EditorLine_pushButton.setText(_translate("MainWindow", "Line"))
        self.image1EditorFill_pushButton.setText(_translate("MainWindow", "Fill"))
        self.image1EditorColor_label.setText(_translate("MainWindow", "Color"))
        self.image1EditorColor_lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.image1EditorColor_lineEdit.setText(_translate("MainWindow", "128"))
        self.image1EditorPenPixelSize_label.setText(_translate("MainWindow", "PenPixelSize"))
        self.image1EditorPenPixelSize_lineEdit.setText(_translate("MainWindow", "5"))
        self.loadImage1_pushButton.setText(_translate("MainWindow", "Load Image1"))
        self.loadImage2_pushButton.setText(_translate("MainWindow", "Load Image2"))
        self.zoom_label.setText(_translate("MainWindow", " Zoom In/Out"))
        self.zoomCenterX_label.setText(_translate("MainWindow", "Zoom Center: X"))
        self.zoomCenterY_label.setText(_translate("MainWindow", "Y"))
        self.image1Alpha_label_2.setText(_translate("MainWindow", "Image Blending Ratio"))
        self.image1Alpha_label.setText(_translate("MainWindow", "Image1 "))
        self.image2Alpha_label.setText(_translate("MainWindow", "Image2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

